# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f9a26fb7f5778940e3ddce211e8ceda74d9b37f901576f154214c2fe3e8c34fad0650a60345f40aaa0b1fd18c643b19afc3512bf3fe3341c6c4ac7b1a440c17

test:
  secret_key_base: e96ce4b69cb777109e811b25e55369d61c5438f1d0731c11f6ba617ad44b97e732250d22efff25db885744a9b25f11887cf2217ccff9011dc9630ed1c10c737c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
